### PR TITLE
feat: for APPLAUNCHER-28 various data fixes

### PR DESCRIPTION
**Pull request by Sinjhin**
Changing some data structures so far to make it easier and more apparent where each property from an Ingress or Service is coming from and to align more with the data from Rancher.

Also throwing in here the componentization of the `ClusterActions`, `ClusterGridView`, and `ClusterListView`

Addresses:
- https://krumtest.atlassian.net/browse/APPLAUNCHER-28
- https://krumtest.atlassian.net/browse/APPLAUNCHER-30
- https://krumtest.atlassian.net/browse/APPLAUNCHER-37

Current:
image

┆Issue is synchronized with this [Jira Task](https://krumtest.atlassian.net/browse/APPLAUNCHER-41) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by krumware** [comment]
@Sinjhin Is this ready for review?

**Comment by Sinjhin** [comment]
> @Sinjhin Is this ready for review?

@krumware It is.

**Comment by krumware** [comment]
plz tag me for review so I know, oh and pics or it didn't happen :)

**Comment by Sinjhin** [comment]
@krumware Also throwing in here the componentization of the ClusterActions, ClusterGridView, and ClusterListView

**Review by krumware — APPROVED** [review]
I don't necessarily like how this is positioned (if I turn off the negative margin on the container, it looks like this) 
image

but everything else looks good and that will serve for now. If you can add a tech debt (low priority) for the positioning on that it would be awesome.

**Pull request merged**
