### PR TITLE
feat: for APPLAUNCHER-6 added k8 annotations to global

### PR DESCRIPTION
**Pull request by Sinjhin**
In this screenshot the first global app, gets put there by metadata annotation and shows an unclickable globe. The next two are favorited. Also adds persistence of favorites via `localStorage`.
image

Addresses:
- https://krumtest.atlassian.net/browse/APPLAUNCHER-6
- https://krumtest.atlassian.net/browse/APPLAUNCHER-17
- https://krumtest.atlassian.net/browse/APPLAUNCHER-24
- https://krumtest.atlassian.net/browse/APPLAUNCHER-27

### CODE REVIEW

**Review by krumware — CHANGES_REQUESTED** [review]
Re: the docs. The documentation in the main readme should be more of a directory of extensions, since there will be more extensions than just the app launcher. There is additional text already in the app launcher folder that this can be merged into. 

Otherwise this looks good. I'm adding some more stories for next features in the board.

**Comment by Sinjhin** [comment]
@krumware Sounds good. I am actually going to just remove the documentation in the README I added in that case until we figure out where and how we want to do that. Actually, I noticed you made a story for that so I will comment it there before I remove it.

**Comment by krumware** [comment]
Made the story before I saw the review request. I think your steps are good, maybe just move em to the other readme and it'll start to knock it out

**Comment by Sinjhin** [comment]
> Re: the docs. The documentation in the main readme should be more of a directory of extensions, since there will be more extensions than just the app launcher. There is additional text already in the app launcher folder that this can be merged into.
> 
> Otherwise this looks good. I'm adding some more stories for next features in the board.

Addressed by: [2568eba](https://github.com/krumIO/krum-rancher-extensions/pull/10/commits/2568eba1ab6e6f301f731d508cb7e14657b69b74)

**Pull request merged**
